[phases.setup]
nixPkgs = ["python311", "gcc", "git", "curl"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python -m src.api.main"
