ai:
  provider: none          # one of: none|openai|anthropic|gemini
  model:
    openai: "gpt-5.1"
    anthropic: "claude-3.7"
    gemini: "gemini-2.5-pro-exp"
  max_output_tokens: 2000
  temperature: 0.2
  rate_limit_rps: 1.0

scoring:
  difficulty_weights:
    code_complexity: 0.30
    coupling_blastradius: 0.30
    test_coverage_gap: 0.20
    tooling_fixability: 0.20
  value_weights:
    security_severity: 0.40
    reliability_perf: 0.25
    developer_experience: 0.20
    user_value: 0.15
  scale: 1-5

phasing:
  - name: "Phase 0 – Repo Hygiene"
    include_tags: ["dead_code","formatting","lints","duplicate","infra"]
  - name: "Phase 1 – Security & Safety"
    include_tags: ["security","secrets","sast","auth","input_validation"]
  - name: "Phase 2 – Reliability & Performance"
    include_tags: ["perf","db","io","concurrency","error_handling"]
  - name: "Phase 3 – Developer Experience"
    include_tags: ["tests","typing","docs","build","logging"]
  - name: "Phase 4 – Product Polish"
    include_tags: ["ux","api","observability","i18n"]

tools:
  flake8_config: "config/flake8.cfg"
  bandit_config: "config/bandit.yaml"
  semgrep_rules: "config/semgrep/rules.yaml"

include_exclude: "config/include_exclude.yaml"
